sudo: false
language: haxe
haxe:
  - "3.2.1"
before_install:
  - nvm install v4.6.2
script:
  - haxe -cp haxe/src -cp haxe/test -main RunTests -resource snapshots/snapshot-rev4.json@snapshot-rev4 --interp
  - make bin/husl.min.js
  - node javascript/test.js